research_task:
  name: Research Indian Vegan Recipes
  description: |
    Research traditional Indian vegetarian/vegan recipes and ingredients for {topic}.
    Include:
    - 2-3 historical facts about Indian plant-based cooking
    - Traditional cooking methods and utensils used
    - Common variations of the recipe across regions
  expected_output: A 500-word research report with key findings and sources

outline_task:
  name: Create Blog Outline
  description: |
    Create a blog outline combining story and recipe instructions.
    Include sections for:
    - Family story intro
    - Recipe origins
    - Ingredient list with substitutions
    - Detailed step-by-step cooking instructions
    - Tips and techniques
    - Serving suggestions
  expected_output: Markdown outline with section headers and brief content notes

writing_task:
  name: Write Blog Post
  description: |
    Write the full blog post combining storytelling with clear recipe instructions:
    - Start with family cooking memories
    - Include warm expressions (e.g., "beta", "dear one")
    - Write detailed ingredient measurements
    - Create clear, numbered cooking steps
    - Add chef's notes and tips throughout
    Include placeholders for process photos marked as [IMAGE: description].
  expected_output: A 1000-word blog post in Markdown format

enhancement_task:
  name: Enhance Blog Post
  description: |
    Modernize and digitize the blog post while weaving in grandmother's cherished stories:
      1. Include prep time, cooking time, and servings in a sleek format
      2. Add equipment needed with modern alternatives (Instant Pot, Air Fryer options)
         - Include "How Granny Made It" traditional method
      3. Share life hacks and kitchen gadget recommendations
         - Compare with Granny's time-tested techniques
      4. Include recipe variations optimized for busy lifestyles
         - Highlight Granny's original tips that still work today
      5. Add nutritional facts with focus on trending diets (keto, paleo friendly?)
         - Note Granny's wisdom about balanced eating
      6. Find and embed a single image from unsplash that:
         - Shows traditional cooking
         - Features Instagram-worthy food styling
         - Captures generational cooking connection
      7. Add social media-friendly hashtags (#GrannysKitchenModernized #TraditionMeetsTech)
      8. Include quick scannable tips using emojis
         - Blend modern shortcuts with Granny's secret tips
  expected_output: Enhanced Markdown content, with a single image after the title that bridges generational cooking wisdom with modern tech-savvy approach and remove the backticks
